import "./globals.css";
import Header from "./header";
import Footer from "./footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
      <div className="min-h-screen bg-white text-gray-900">
        <div className="mx-4 md:mx-12">
          <Header />

          <main>{children}</main>

          <Footer />
        </div>
      </div>
      </body>
    </html>
  );
}
